spring:
  application:
    name: fisiowave

  datasource:
    url: jdbc:postgresql://localhost:5432/fisiowave-db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata
    database: POSTGRESQL

  flyway:
    locations: classpath:db/migration,classpath:db/testdata

  mail:
    host: smtp.gmail.com
    port: 587
    username: john.fisiowave@gmail.com
    password: ****
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key